name: 🐛 Bug report
description: Reportar um comportamento incorreto
labels: ["bug", "needs-triage"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: O que aconteceu?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: O que era esperado?
    validations:
      required: true
